# Generated by Django 4.0.1 on 2022-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=8)),
            ],
        ),
    ]
