# Generated by Django 4.0.1 on 2022-09-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='Contact',
        ),
    ]
